library(shiny)
shinyUI(fluidPage(
  title="GameAnalysis",
  titlePanel("GameTrendAnalysis"),
  fluidRow(
    column(4,
           tabsetPanel(
             title="PriceTrend",
             type="pills",
             tabPanel(
               uiOutput("control1")
             ),
             tabPanel(
               uiOutput("control2")
             )        
           )
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("PlotTS",plotOutput("plotTS"))
      )
    ) 
  )
))